seed: 5555
save_dir: outputs/${version}
experiment_id: "vit-${experiment_id:}"
version: ${now:%Y-%m-%d}T${now:%H-%M-%S}-${experiment_id}
valid_ratio: 0.1
test_ratio: 0.2
dataset:
  imgs_dir: "/home/kuon/workspace/data/images/annotated"
  img_ext: ".jpg"
  label_path: "/home/kuon/workspace/data/preprocess-for-ml/data/labeled-dataset/labeled-dataset.json"
  label_type: "imp_all"
  max_frame: 1000
  vtuber_info_path: "/home/kuon/workspace/data/vtuber-scraper/dataset/merged.json"
train:
  max_epoch: 100
  batch_size: 32
  lr: 0.001
  train_final_layer_only: true

hydra:
  run:
    dir: ${save_dir}
  sweep:
    dir: ${save_dir}
    subdir: ${hydra.job.num}
